### ISSUE TITLE
Plugin collision occurs when trying to use base and typescript configs

### ISSUE THREAD

**Issue by Tauka** [eslint-kit/eslint-config-kit#13]
Hello, thank you for this package! I have faced an error when trying to use both `/base` and `/typescript` configs,

```
Oops! Something went wrong! :(

ESLint: 7.26.0

ESLint couldn't determine the plugin "import" uniquely.

- /Users/tauka/Documents/dynamik/robotmation/three-editor/node_modules/@eslint-kit/eslint-config-typescript/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @eslint-kit/eslint-config-typescript")
- /Users/tauka/Documents/dynamik/robotmation/three-editor/node_modules/@eslint-kit/eslint-config-base/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @eslint-kit/eslint-config-base")

Please remove the "plugins" setting from either config or remove either plugin installation.
```

**Comment by risenforces** [comment]
@Tauka Hello! It's not the `@eslint-kit`'s issue. Most likely, your starter (cra, gatsby, etc) has `eslint-import-plugin` inside, which is why versions conflict in some way. I need information about what exactly you are using and I can help.

**Comment by Tauka** [comment]
I was able to reproduce error in minimal repo: https://github.com/Tauka/eslint-config-kit-issue

Seems like issue only occurs when you install `eslint-plugin-import` as your dependency even though it is not added to `.eslintrc.js`. When I remove it (npm uninstall or yarn remove), it works fine. I still think this behavior is incorrect, if someone has `eslint-plugin-import` installed in their `node_modules`, then those configs won't work.
